# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
branches:
  only:
    - master
os:
  - linux
julia:
  - 1
#  - nightly
#matrix:
#  allow_failures:
#    - julia: nightly
notifications:
  email: false
#env:
#   - PYTHON=""
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd())'
#  - julia -e 'Pkg.test("DifferentialEquations")'
